version: '2'
services:
  postgres:
    image: existquadx/xpay-postgres:1.0
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data

#  ampota-ui-frontend:
#    image: ampota/ampota-ui-frontend:1.0
#    network_mode: "host"
#    container_name: ampota-ui-frontend

  xpay-discovery:
    image: existquadx/xpay-discovery:1.0
    network_mode: "host"
    container_name: ampota-discovery

  ampota-gateway:
    image: ampota/ampota-gateway:1.0
    network_mode: "host"
    depends_on:
    - xpay-discovery
    container_name: ampota-gateway
    volumes:
    - "/home/markbbmartinez/ampota/uploads:/uploads"
    environment:
    - "spring.cloud.stream.binders.local_rabbit.environment.spring.rabbitmq.host=localhost"

  ampota-user:
    image: ampota/ampota-user:1.0
    network_mode: "host"
    depends_on:
    - postgres
    - xpay-discovery
    container_name: ampota-user
    environment:
    - "spring.cloud.stream.binders.local_rabbit.environment.spring.rabbitmq.host=localhost"

  ampota-card:
    image: ampota/ampota-card:1.0
    network_mode: "host"
    depends_on:
    - postgres
    - xpay-discovery
    container_name: ampota-card
    volumes:
    - "/home/markbbmartinez/ampota/scryfall_bulk_json:/scryfall_bulk_json"
    environment:
    - "spring.cloud.stream.binders.local_rabbit.environment.spring.rabbitmq.host=localhost"

volumes:
  db_data: