management:
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8090

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

spring:
  application:
    name: ampota-gateway
  cloud.stream:
    bindings:
      auditChannel:
        destination: auditChannel
        binder: local_rabbit
    binders:
      local_rabbit:
        type: rabbit
        environment:
          spring:
            rabbitmq:
              host: xpay-staging.manila.exist.com
              port: 5672
              username: rabbitmq
              password: rabbitmq

hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isoaltion.threadtimeout.InMilliseconds: 300000
ribbon.ReadTimeout: 360000
ribbon.ConnectTimeout: 360000

firebase.config-file: xpay-test-firebase-key.json
